/* eslint-disable linebreak-style */
const enLang = [
  [
    {
      key: '2',
      name: '2',
      nameShift: '@',
      keyCode: 50,
      code: 'Digit2',
      location: 0,
      description: '2 Key',
      unicode: '②',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: '3',
      name: '3',
      nameShift: '#',
      keyCode: 51,
      code: 'Digit3',
      location: 0,
      description: '3 Key',
      unicode: '③',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: '5',
      name: '5',
      nameShift: '%',
      keyCode: 53,
      code: 'Digit5',
      location: 0,
      description: '5 Key',
      unicode: '⑤',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: '6',
      name: '6',
      nameShift: '^',
      keyCode: 54,
      code: 'Digit6',
      location: 0,
      description: '6 Key',
      unicode: '⑥',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: '7',
      name: '7',
      nameShift: '&',
      keyCode: 55,
      code: 'Digit7',
      location: 0,
      description: '7 Key',
      unicode: '⑦',
      class: 'shortkey',
      property: 'printable',
    },
  ],
  [
    {
      key: 'q',
      name: 'q',
      nameShift: 'Q',
      keyCode: 81,
      code: 'KeyQ',
      location: 0,
      description: 'q',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: 'w',
      name: 'w',
      nameShift: 'W',
      keyCode: 87,
      code: 'KeyW',
      location: 0,
      description: 'w',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: 'e',
      name: 'e',
      nameShift: 'E',
      keyCode: 69,
      code: 'KeyE',
      location: 0,
      description: 'e',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: 'r',
      name: 'r',
      nameShift: 'R',
      keyCode: 82,
      code: 'KeyR',
      location: 0,
      description: 'r',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: 't',
      name: 't',
      nameShift: 'T',
      keyCode: 84,
      code: 'KeyT',
      location: 0,
      description: 't',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: 'y',
      name: 'y',
      nameShift: 'Y',
      keyCode: 89,
      code: 'KeyY',
      location: 0,
      description: 'y',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: 'u',
      name: 'u',
      nameShift: 'U',
      keyCode: 85,
      code: 'KeyU',
      location: 0,
      description: 'u',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: 'i',
      name: 'i',
      nameShift: 'I',
      keyCode: 73,
      code: 'KeyI',
      location: 0,
      description: 'i',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: 'o',
      name: 'o',
      nameShift: 'O',
      keyCode: 79,
      code: 'KeyO',
      location: 0,
      description: 'o',
      class: 'shortkey',
      property: 'printable',
    },
    {
      key: 'p',
      name: 'p',
      nameShift: 'P',
      keyCode: 80,
      code: 'KeyP',
      location: 0,
      description: 'p',
      class: 'shortkey',
      property: 'printable',
    },
  ],
];

export default enLang;
